version: '3.3'

services:
  database:
    image:
      'postgres:latest'
    container_name: dorm-deals-postgres-1
    networks:
      - cloud
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresPassword
      - POSTGRES_DB=DormDeals
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
    image:
      'redis:latest'
    container_name: dorm-deals-redis-1
    networks:
      - cloud
    ports:
      - "6380:6379"
    volumes:
      - redis_volume:/data


  application:
    image:
      dorm-deals-application-image
    container_name: dorm-deals-app-1
    networks:
      - cloud
    ports:
      - "80:8080"
    depends_on:
      - database
      - redis
    environment:
      - "SPRING_SERVER_PORT=8080"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/DormDeals"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=postgresPassword"
      - "SPRING_JWT_SECRET=secret"

volumes:
  postgres_volume:
    external: true
  redis_volume:
    external: true

networks:
  cloud:
    external: true
